export const resumeConstants = {
  RESUME_FORMAT:"RESUME_FORMAT",
  PERSONAL_DETAILS: "PERSONAL_DETAILS",
  PROFILE_SUMMARY: "PROFILE_SUMMARY",
  EXPERIENCE: "EXPERIENCE",
  EDUCATION: "EDUCATION",
  SKILLS: "SKILLS",
  PERSONAL_PROJECTS: "PERSONAL_PROJECTS",
  LANGUAGES: "LANGUAGES",
  VOLUNTEER_WORK: "VOLUNTEER_WORK",
  CERTI_AND_AWARDS: "CERTI_AND_AWARDS",
};
